### PR TITLE
Readme: Added attribution to The Cube by ProfiCNC

### PR DESCRIPTION
**Pull request by lordneeko**
and link to CC license.

### CODE REVIEW

**Comment by ChristopherOlson** [comment]
@lordneeko perhaps squash your last two commits to make the pull a little cleaner.

**Comment by lordneeko** [comment]
That's not in my skill set sorry.

**Comment by ChristopherOlson** [comment]
git rebase -i HEAD~2

Change the last commit from pick to s and save it, which will squash it into the previous commit, then edit the commit message to reflect it as being a single commit. Then git push -f which will update the PR.
Thanks!

**Comment by lordneeko** [comment]
I don't have git access. ;) I have access to github, that's it. If it can't be done on github, I can't do it.
thanks.

**Comment by GuyMcCaldin** [comment]
If any part of the design used ProfiCNC files shared under CC-BY-SA 3.0 and CC-BY-NC 3.0 licenses, CUAV have an obligation to comply with the license requirements.  It doesn't matter how much of the design was changed, it's still a derivative by the definition of the license.  

It's not necessary to interpret whether this happened or not.  CUAV effectively acknowledges that the design files were used in the existing README.md:

> Including PX4\PIXHAWK\3DR\Proficnc\ST\Altium\TDK\Hirose\Hrs\PANASONIC\molex\TI\ and other organizations or companies.Some design reference copyrights should belong to them. 

CUAV had the free choice not to use the ProfiCNC design files.  By choosing to use them, they explicitly agreed to the license terms.

The requirements for attribution are listed on the [license page](https://wiki.creativecommons.org/wiki/License_Versions#Attribution_and_marking) linked from the [ProfiCNC github](https://github.com/proficnc/The-Cube).  These terms are provided in [Mandarin ](https://creativecommons.org/licenses/by-sa/3.0/deed.zh), so language barriers are not a valid excuse.

To comply, CUAV at the very least need to specify the title of the design files used, provide a link to the original material, and reproduce copyright notices supplied with the original design.  Examples for how this works are linked from the license page: [Best practices for attribution](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution).

**Comment by ChristopherOlson** [comment]
I was not able to find any design files from ProfiCNC. Those are not open. Only schematics. If this is by some stretch the case, comparing the two reveals that the core module is not the same, and the I/O board is so totally different it's not even possible to compare. CUAV used a genuine Hirose DF17 connector, there is no USB port in the module, the dimensions aren't even the same between the two, nor is the disassembly procedure the same.

IMO even giving attribution to styling cues is really stretching it. Apple in the hardware business tries to patent styling to lock competitors out - sometimes they are successful, the majority of those applications are rejected. ProfiCNC claims patent on the Cube shape, but nowhere can those patent filings be found in any search in the US, Europe or Australia.

It is the styling of the product that has rattled cages. If it were put in a rectangular box like the Pixhawk 4 the claims wouldn't have even surfaced. But nowhere (other than the claimed patent on Cube shape) is styling mentioned in the licenses and I would have to study that patent filing to see if there is even an infringement there. Any patent granted on a Cube shape would have to have very specific features to make it patent-able, and being you can set the two "cubes" on the bench and see visually they are not the same thing, that is an extreme stretch of the imagination. And more likely an effort to just lock out competition.

Otherwise the design of the IMU is consistent with the Pixhack V3, except with dual IMU's instead of triple. The design of the FMU is an obvious derivative of the FMUv5, which is not even close the Cube. That doesn't mean some things inside can't be the same such as sensors, heating resistors, or even some similarity in circuit design, as some circuits are pretty standard in EE. But my evaluation of the product is that it is an evolution of the Pixhack V3 updated to v5, and the one and only similarity I could see to the Cube is in the way it looks at first glance.

So if the claim wants to be made that design files were used, those design files have to be produced and prove it. Otherwise CUAV has complied 100% with the CC license. Because in my examination here, if you took the drawings for the Cube and tried to turn it into what the Pixhack V5 is, you may as well wipe the file out of your computer and start over - it is that significantly and fundamentally different. I think it is was more like, "hey - we can make a product that looks like that, as the stacked design does have some advantages - let's design one". But if you take a digital caliper and measure the two up even the dimensions are TOTALLY different. The module on the V5 is not even in the same place on the I/O and the case of the Cube's carrier is 94mm, the case of the I/O on the V5 is 90mm. Even the width is narrower by 2.5mm - the V5 is a physically smaller unit.

I would concede on the styling issue if it's even required to provide attribution for that. I don't think it is any more than one manufacturer of a rectangular one having to provide attribution to another manufacturer of a rectangular one. But out of courtesy it's not a bad idea as it is obvious it was - so I think this PR is good from that respect.

Anything else will have to be proven beyond a shadow of a doubt, and based on my detailed examination of the units, this is going to very hard to do.

**Comment by GuyMcCaldin** [comment]
Design files include schematics.  How to apply the license is not something that's open to alternative interpretation.  [From the license:](https://creativecommons.org/licenses/by-sa/3.0/legalcode)

> BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND CONDITIONS.

> "Work" means the literary and/or artistic work offered under the terms of this License including without limitation any production in the literary, scientific and artistic domain, whatever may be the mode or form of its expression including digital form, such as a book, pamphlet and other writing; a lecture, address, sermon or other work of the same nature; a dramatic or dramatico-musical work; a choreographic work or entertainment in dumb show; a musical composition with or without words; a cinematographic work to which are assimilated works expressed by a process analogous to cinematography; a work of drawing, painting, architecture, sculpture, engraving or lithography; a photographic work to which are assimilated works expressed by a process analogous to photography; a work of applied art; an illustration, map, plan, sketch or three-dimensional work relative to geography, topography, architecture or science; a performance; a broadcast; a phonogram; a compilation of data to the extent it is protected as a copyrightable work; or a work performed by a variety or circus performer to the extent it is not otherwise considered a literary or artistic work.

> "Adaptation" means a work based upon the Work, or upon the Work and other pre-existing works, such as a translation, adaptation, derivative work, arrangement of music or other alterations of a literary or artistic work, or phonogram or performance and includes cinematographic adaptations or any other form in which the Work may be recast, transformed, or adapted **including in any form recognizably derived from the original,** except that a work that constitutes a Collection will not be considered an Adaptation for the purpose of this License.

> "Reproduce" means to make copies of the Work by any means including without limitation by sound or visual recordings and the right of fixation and reproducing fixations of the Work, including storage of a protected performance or phonogram in digital form or other electronic medium.

> You may Distribute or Publicly Perform the Work only under the terms of this License. You may not offer or impose any terms on the Work that restrict the terms of this License or the ability of the recipient of the Work to exercise the rights granted to that recipient under the terms of the License. You may not sublicense the Work. You must keep intact all notices that refer to this License and to the disclaimer of warranties with every copy of the Work You Distribute or Publicly Perform. When You Distribute or Publicly Perform the Work, You may not impose any effective technological measures on the Work that restrict the ability of a recipient of the Work from You to exercise the rights granted to that recipient under the terms of the License. 

> No term or provision of this License shall be deemed waived and no breach consented to unless such waiver or consent shall be in writing and signed by the party to be charged with such waiver or consent.

The terms of the license are necessarily broad to protect the interests of the original author of work.  You might not agree with how this works, but even if a single feature was used from the ProfiCNC design (which by their own acknowledgement has occured), the entire V5 design needs to conform with the above.  

Again, this is a free choice CUAV have made.

These requirements obviously extent to other copyright holders who's CC licensed work was used or referenced in the design of the V5, not just ProfiCNC.  Certainly this should include 3DR and PX4, given that earlier versions of the PixHack which influenced this design were derivatives of the Pixhawk.

**Comment by ChristopherOlson** [comment]
I believe CUAV already has this relationship with PX4, and has for a long time
https://docs.px4.io/en/flight_controller/pixhack_v5.html

CUAV states:
> The PixHack V5 is based on the FMUv5 designed flight control controller hardware.

> The main design of the PixHack V5 hardware is performed by CUAV and produced by CUAV.

> The hardware design file is completely open by CUAV and And abide by the CC-BY-SA 3.0 license.

> The PixHack V5 design document cites many design files or reference files and related libraries from these organizations or companies.

> Including PX4\PIXHAWK\3DR\Proficnc\ST\Altium\TDK\Hirose\Hrs\PANASONIC\molex\TI\ and other organizations or companies.Some design reference copyrights should belong to them.

ProfiCNC states:
> The Cube Black Hardware is the result of a collaboration of the PX4, Ardupilot community, 3D Robotics, ProfiCNC and Hex Technologies and has been designed in Altium. Pixhawk 2 FMUv3 is a derivitive of the Pixhawk 1, APM, PX4 project. The IMU is an original ProfiCNC work

Why would you hold CUAV to a higher standard than ProfiCNC? It appears they both pretty much state the same thing.

**Comment by ChristopherOlson** [comment]
@GuyMcCaldin since my review, examination of the build, and testing of the Pixhack V5 turned up no evidence that any design files were taken without attribution perhaps consider submitting a PR to correct what you think is a violation of the license. CUAV will either merge it, or reject it if it doesn't apply.

Otherwise all outward appearances are that there is simply an attempt at leveraging unfounded claims in an attempt to create a non-competition environment in the open hardware market to benefit one manufacturer. Since you seem to know where the infraction is, as CUAV being one of our ArduPilot Partners, please help them resolve it. This is an important piece of hardware for the community since some of the developers will want to take advantage of its capabilities and further optimize future versions of the code for it. It is the only FMUv5 controller we presently officially support. And CUAV was thoughtful enough to provide us with hardware so we could support it, instead of having it just supported by PX4.

Thanks!

**Comment by GuyMcCaldin** [comment]
> Why would you hold CUAV to a higher standard than ProfiCNC? It appears they both pretty much state the same thing.

Because Philip Rowse, along with Jeff Wurzbach, hold the original copyright to the Pixhawk 2 design that the Cube was based on.

**Comment by GuyMcCaldin** [comment]
@ChristopherOlson I'd suggest you're being deliberately obtuse for the sake of continuing the argument, or you haven't invested the necessary time to understand the licence.  You're certainly not responding to arguments being made.

**Comment by ChristopherOlson** [comment]
I would suggest this PR be closed by @lordneeko It doesn't apply to the licensing requirements at all.

And yes I understand the license perfectly well. But CUAV is not the one with licensing issues and claims of patented cube shapes when patents don't exist. That raises some serious alarms right there.

**Comment by GuyMcCaldin** [comment]
> since my review, examination of the build, and testing of the Pixhack V5 turned up no evidence that any design files were taken without attribution

As mentioned in my opening comment, CUAV are already on public record acknowledging the use of ProfiCNC, 3DR, and PX4 copyrighted works.  There is no attribution provided in the current README that satisfies the requirements of the CC-BY-SA 3.0 licence.

> And yes I understand the license perfectly well.

I apologies for being so direct, but you've demonstrated repeatedly that you don't.  I'm assuming you're relying on a general interpretation of how you think open source licences _should work_, instead of reading and applying the _actual legal code_ of the CC-BY-SA and CC-BY-NC 3.0 licences in question.  They are open ended to the extent that they're described as a [Viral licence](https://en.wikipedia.org/wiki/Viral_license).

> But CUAV is not the one with licensing issues and claims of patented cube shapes when patents don't exist.

Again, this demonstrates that you don't understand how these licences work.  The Pixhawk 2 was a greenfield project that was not a derivative of existing PX4 works, but was created with input from the PX4 project.  Philip Rowse is the original copyright owner, and this means that he can release the designs under any licence he chooses, even releasing the same design under multiple licences. 

Regarding the patent, I completely agree with you on this point.  I wasn't able to find any reference to it, and I think it's a community hostile move by ProfiCNC.  However, this a [Tu quoque fallacy](https://en.wikipedia.org/wiki/Tu_quoque) that doesn't belong in a discussion about CUAV.

I honestly don't think we're going to find any common ground, but these are the facts as I see them:

1. Critical to the claim of licence violations is the existing attempt at attribution that acknowledges ProfiCNC copyrighted works were used, and that ProfiCNC believe their copyright has been violated
2. There is a clear resemblance between the designs, though the vast majority of the V5 is original work
3. There is evidence that features have been directly copied from copyrighted ProfiCNC works, the clearest example being the IMU heater
4. The terms of the licence define adaption as _"any form recognizably derived from the original"_
5. A [Reasonable Person](https://en.wikipedia.org/wiki/Reasonable_person) would recognise the the V5 as a derivative of the Cube
6. There is well established cultural ignorance when it comes to managing intellectual property rights in China (which is a blameless statement, but still an important factor)

All CUAV need to do to gain my support is comply with the licences for the design files they've already acknowledged they've used.

**Comment by ChristopherOlson** [comment]
New claims are being made every day where the Cube is concerned. PX4.io's documentation states
> The Cube flight controller (previously known as Pixhawk 2.1) is a flexible autopilot intended primarily for manufacturers of commercial systems. **It is based on the Pixhawk-project FMUv3 open hardware design** and runs PX4 on the NuttX OS.

I pinged Lorenz to take a look. I don't believe CUAV to be out of compliance. The clearly hostile actions taken by ProfiCNC in recent weeks, obviously designed to squelch competition from a new product, are highly questionable. Attribution cannot be given to claims that don't exist.

Again, I would suggest just closing this PR. It is not applicable.

**Comment by GuyMcCaldin** [comment]
> New claims are being made every day where the Cube is concerned.  ...   It is based on the Pixhawk-project FMUv3 

Please, for the sake of due diligence, go to the [FMUv3 PX4 hardware directory](https://github.com/PX4/Hardware/tree/master/FMUv3_REV_D/Schematic%20Print), and read the name listed on the schematic.  This is the copyright holder.

> I don't believe CUAV to be out of compliance.

Can you show me where they've provided any attribution that satisfied the licence requirements?

> The clearly hostile actions taken by ProfiCNC in recent weeks, obviously designed to squelch competition from a new product, are highly questionable. Attribution cannot be given to claims that don't exist.

An alternative explanation is that CUAV have violated open source licences by failing to provide proper attribution, and copying features protected by a Non-Commercial clause like the IMU heater design.

**Comment by lordneeko** [comment]
I'm tired of getting emails on this. You guys feel free to argue here if you want. Create your own pull request when you're happy.

**Pull request closed without merging**
